---
- hosts: prod
  become: yes
  remote_user: root
  roles:

  - supervisord

  - ssl-certs

  - role: nginx
    nginx_http_params:
      - sendfile "on"
      - access_log "/var/log/nginx/access.log"
      - gzip on
      - keepalive_timeout 65
      - client_max_body_size 20M
      - rewrite_log on
    nginx_configs: 
      ssl:
        - ssl_certificate_key {{ssl_certs_privkey_path}}
        - ssl_certificate     {{ssl_certs_cert_path}}
        - ssl_protocols TLSv1 TLSv1.1 TLSv1.2
        - ssl_ciphers "AES128+EECDH:AES128+EDH"
        - ssl_prefer_server_ciphers on
        - ssl_session_cache shared:SSL:10m
      proxy:
        - proxy_set_header Host $host
        - proxy_set_header X-Real-IP $remote_addr
        - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
        - proxy_set_header X-Forwarded-Proto $scheme
        - proxy_max_temp_file_size 0
        - proxy_read_timeout 120s
    nginx_sites:
      # rewrite all requests on port 80 to 443
      default:
        - listen 80 default_server
        - rewrite ^ https://$host$request_uri? permanent
      # everything else gets proxied through the authproxy
      authproxy:
        - listen 443 ssl default_server
        - location / { proxy_pass http://127.0.0.1:7000; }

  - role: authproxy
    reverse_proxies:
    - domain: site1.internal.laughinghyena.com
      to: http://127.0.0.1:8081
    - domain: site2.internal.laughinghyena.com
      to: http://127.0.0.1:8082
    - domain: site3.internal.laughinghyena.com
      to: http://127.0.0.1:8083
      identity_required: true
    whitelisted_ips:
    - ip: 212.111.111.1
      description: office1
    - ip: 212.111.111.2
      description: office2
